import os
import json
import shutil
from datetime import datetime
from sheets_manager import SheetsManager
from notifications import NotificationManager
from receipt_processor import ReceiptProcessor

def test_notifications_flow():
    print("=== STARTING NOTIFICATIONS TEST ===")
    
    # Initialize SheetsManager
    sm = SheetsManager()
    
    # Clear logs to start fresh in our test
    sm.data["notification_logs"] = []
    
    # Ensure Unit 101 has contacts
    unit_101 = next((u for u in sm.data["units"] if u["id"] == "101"), None)
    assert unit_101 is not None, "Unit 101 should exist"
    assert unit_101.get("email1") == "carlos@test.com", "Unit 101 owner email should be carlos@test.com"
    assert unit_101.get("email2") == "maria@test.com", "Unit 101 tenant email should be maria@test.com"
    
    # Let's create a pending aliquot for Unit 101
    aliquot_id = "101-2026-Junio"
    # Remove if exists
    sm.data["aliquots"] = [a for a in sm.data["aliquots"] if a["id"] != aliquot_id]
    sm.data["aliquots"].append({
        "id": aliquot_id,
        "unit": "101",
        "month": "Junio",
        "year": 2026,
        "amount": 70.0,
        "late_fee": 0.0,
        "payment_date": "2026-06-10",
        "reference": "DEP-778899", # Not reconciled yet
        "status": "Validación Manual"
    })
    
    # Add matching bank transaction
    sm.data["bank_statement"] = [b for b in sm.data["bank_statement"] if b["reference"] != "DEP-778899"]
    sm.data["bank_statement"].append({
        "date": "2026-06-10",
        "reference": "DEP-778899",
        "amount": 70.0,
        "detail": "TRANSF Carlos Mendoza 101",
        "reconciled": False
    })
    
    sm.sync()
    
    print("1. Running mass reconciliation for Unit 101...")
    aliquots_reconciled, charges_reconciled = sm.reconcile_mass()
    
    print(f"Reconciled: Aliquots={aliquots_reconciled}, Charges={charges_reconciled}")
    assert aliquots_reconciled == 1, "Should have reconciled 1 aliquot"
    
    # Check if notification logs were created
    logs = sm.data.get("notification_logs", [])
    print(f"Notification logs created: {len(logs)}")
    
    # Since Unit 101 has Owner (email1, phone1) and Tenant (email2, phone2)
    # and both channels are populated (email and phone), we expect:
    # Owner: Email, WhatsApp
    # Tenant: Email, WhatsApp
    # Total: 4 notification log entries
    assert len(logs) == 4, f"Expected 4 notification log entries, got {len(logs)}"
    
    # Verify that all logs are in "Simulado" mode
    for log in logs:
        assert log["mode"] == "Simulado", f"Expected Simulado mode, got {log['mode']}"
        assert log["status"] == "Enviado", f"Expected status Enviado, got {log['status']}"
        print(f"[{log['channel']}] to {log['recipient']} ({log['destination']}) - Status: {log['status']} ({log['mode']})")
        
    print("[OK] Mass reconciliation notification test PASSED!")
    
    # Test Individual Resend
    print("\n2. Simulating individual receipt resending...")
    # Generate/locate the PDF receipt
    receipts_dir = os.path.join(os.path.dirname(__file__), "static", "receipts")
    os.makedirs(receipts_dir, exist_ok=True)
    pdf_filename = f"recibo_{aliquot_id}.pdf"
    pdf_path = os.path.join(receipts_dir, pdf_filename)
    
    # Ensure PDF exists (it was generated by mass reconciliation, let's verify)
    assert os.path.exists(pdf_path), f"Expected PDF at {pdf_path} to exist"
    
    # Clear logs to isolate resend logs
    sm.data["notification_logs"] = []
    sm.sync()
    
    # Run notifications resending
    resend_results = NotificationManager.send_receipt_notifications(
        sm=sm,
        unit_id="101",
        receipt_pdf_path=pdf_path,
        receipt_no=f"REC-AL-{aliquot_id}",
        resident_name="Carlos Mendoza",
        concept="Pago de Alícuota Ordinaria - Mes: Junio / 2026",
        amount=70.0,
        payment_date="2026-06-10",
        reference="DEP-778899"
    )
    
    assert resend_results is not None, "Resend results should not be None"
    assert len(resend_results) == 4, f"Expected 4 resend logs, got {len(resend_results)}"
    
    logs_after_resend = sm.data.get("notification_logs", [])
    assert len(logs_after_resend) == 4, f"Expected 4 notification logs in DB after resend, got {len(logs_after_resend)}"
    print("[OK] Individual resend notification test PASSED!")
    
    # Clean up test aliquot and bank statement
    sm.data["aliquots"] = [a for a in sm.data["aliquots"] if a["id"] != aliquot_id]
    sm.data["bank_statement"] = [b for b in sm.data["bank_statement"] if b["reference"] != "DEP-778899"]
    sm.sync()
    print("=== NOTIFICATIONS TEST PASSED SUCCESSFULLY ===")

if __name__ == "__main__":
    test_notifications_flow()
